version: '3.8'
services:
  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/product-service
    depends_on:
      - mongodb
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/order-service
    depends_on:
      - mongodb
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/user-service
    depends_on:
      - mongodb
    networks:
      - microservices-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - product-service
      - order-service
      - user-service
    networks:
      - microservices-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data: 