apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.documentdb.secretName | default "documentdb-credentials" }}
  namespace: {{ .Values.documentdb.namespace | default "dev" }}
spec:
  refreshInterval: {{ .Values.documentdb.refreshInterval | default "1h" }}
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Values.documentdb.secretName | default "documentdb-credentials" }}
    template:
      type: Opaque
      data:
        MONGODB_URI: mongodb://{{ "{{ .username }}" }}:{{ "{{ .password }}" }}@{{ "{{ .host }}" }}:27017/microstore?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.documentdb.awsSecretKey }}
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .Values.documentdb.awsSecretKey }}
      property: password
  - secretKey: host
    remoteRef:
      key: {{ .Values.documentdb.awsSecretKey }}
      property: host 