apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.frontend.name }}
  labels:
    app: {{ .Values.services.frontend.name }}
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.services.frontend.name }}
          image: {{ .Values.services.frontend.image }}
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
          env:
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8080"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:8081"
          resources:
            {{- toYaml .Values.services.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3

 