apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.frontend.name }}
  labels:
    app: {{ .Values.services.frontend.name }}
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.services.frontend.name }}
          image: {{ .Values.services.frontend.image }}
          ports:
            - containerPort: {{ .Values.services.frontend.port }}
          env:
            - name: PRODUCT_SERVICE_URL
              value: "http://{{ .Values.services.product.name }}:{{ .Values.services.product.port }}"
            - name: ORDER_SERVICE_URL
              value: "http://{{ .Values.services.order.name }}:{{ .Values.services.order.port }}"
          resources:
            {{- toYaml .Values.services.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: {{ .Values.services.frontend.probes.readiness.initialDelay | default 10 }}
            periodSeconds: {{ .Values.services.frontend.probes.readiness.period | default 5 }}
            timeoutSeconds: {{ .Values.services.frontend.probes.readiness.timeout | default 2 }}
            successThreshold: {{ .Values.services.frontend.probes.readiness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.services.frontend.probes.readiness.failureThreshold | default 3 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: {{ .Values.services.frontend.probes.liveness.initialDelay | default 15 }}
            periodSeconds: {{ .Values.services.frontend.probes.liveness.period | default 10 }}
            timeoutSeconds: {{ .Values.services.frontend.probes.liveness.timeout | default 2 }}
            successThreshold: {{ .Values.services.frontend.probes.liveness.successThreshold | default 1 }}
            failureThreshold: {{ .Values.services.frontend.probes.liveness.failureThreshold | default 3 }}

 