{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-{{ .Release.Namespace }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }} 