{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
