apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.karpenter.nodePool.name | default "default" }}
  namespace: {{ .Values.karpenter.namespace | default "karpenter" }}
spec:
  disruption:
    consolidateAfter: {{ .Values.karpenter.nodePool.disruption.consolidateAfter | default "30s" }}
    consolidationPolicy: {{ .Values.karpenter.nodePool.disruption.consolidationPolicy | default "WhenEmptyOrUnderutilized" }}
  limits:
    cpu: {{ .Values.karpenter.nodePool.limits.cpu | default "100" | quote }}
    memory: {{ .Values.karpenter.nodePool.limits.memory | default "400Gi" | quote }}
  template:
    spec:
      nodeClassRef:
        kind: EC2NodeClass
        name: {{ .Values.karpenter.nodeClass.name | default "default" }}
        group: karpenter.k8s.aws
      expireAfter: {{ .Values.karpenter.nodePool.expireAfter | default "720h" }}
      requirements:
        {{- with .Values.karpenter.nodePool.requirements }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  weight: {{ .Values.karpenter.nodePool.weight | default 10 }} 