apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.order.name }}
  labels:
    app: {{ .Values.services.order.name }}
spec:
  replicas: {{ .Values.services.order.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.order.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.order.name }}
    spec:
      containers:
        - name: {{ .Values.services.order.name }}
          image: {{ .Values.services.order.image }}
          ports:
            - containerPort: {{ .Values.services.order.port }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.order.mongodb.secretName }}
                  key: {{ .Values.services.order.mongodb.secretKey }}
          resources:
            {{- toYaml .Values.services.order.resources | nindent 12 }}