apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.product.name }}
  labels:
    app: {{ .Values.services.product.name }}
spec:
  replicas: {{ .Values.services.product.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.product.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.product.name }}
    spec:
      containers:
        - name: {{ .Values.services.product.name }}
          image: {{ .Values.services.product.image }}
          ports:
            - containerPort: {{ .Values.services.product.port }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: {{ .Values.services.product.mongodb.uri }}
          resources:
            {{- toYaml .Values.services.product.resources | nindent 12 }}