apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.product.name }}
  labels:
    app: {{ .Values.services.product.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.product.port }}
      targetPort: {{ .Values.services.product.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.product.name }} 