name: CI/CD

on:
  push:
    branches: [ dev, staging, main ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for product-service..."
          while ! curl -f http://localhost:8080/api/products; do sleep 5; done
          echo "Waiting for order-service..."
          while ! curl -f http://localhost:8081/api/orders; do sleep 5; done
          echo "Waiting for frontend..."
          while ! curl -f http://localhost:80; do sleep 5; done
          
      - name: Cleanup
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    env:
      AWS_REGION: us-east-1
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        service: [frontend, product-service, order-service]
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767397741479:role/GithubRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to ECR
        id: build-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: microstore
          IMAGE_TAG: ${{ matrix.service }}-${{ github.ref_name }}-${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}/.
          
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image \
            --exit-code 1 \
            --ignore-unfixed \
            --vuln-type os,library \
            --severity HIGH,CRITICAL \
            $REGISTRY/$REPOSITORY:$IMAGE_TAG
            
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "${{ matrix.service }}_IMAGE_URI=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  update-gitops:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: nadavcool543/gitops-repo
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-repo

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          
      - name: Update image tags in values.yaml
        run: |
          cd gitops-repo/environments/${{ github.ref_name }}
          yq eval ".services.frontend.image = \"${{ needs.deploy.outputs.frontend_IMAGE_URI }}\"" -i values.yaml
          yq eval ".services.product.image = \"${{ needs.deploy.outputs.product-service_IMAGE_URI }}\"" -i values.yaml
          yq eval ".services.order.image = \"${{ needs.deploy.outputs.order-service_IMAGE_URI }}\"" -i values.yaml
          
      - name: Commit and push changes
        run: |
          cd gitops-repo
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update ${{ github.ref_name }} environment images to ${{ github.sha }}"
          git push